class DatabaseImages {
  static List<Map> databaseImagesDepartment = [
    {
      "id": 1,
      "image": "assets/images/doctors_department/drug.png",
      "department": "General Medicine",
    },
    {
      "id": 2,
      "image": "assets/images/doctors_department/cancer.png",
      "department": "Oncology Department",
    },
    {
      "id": 3,
      "image": "assets/images/doctors_department/surgery.png",
      "department": "Surgery Department"
    },
    {
      "id": 4,
      "image": "assets/images/doctors_department/emergency.png",
      "department": "Emergency Department"
    },
    {
      "id": 5,
      "image": "assets/images/doctors_department/brain.png",
      "department": "Neurology Department",
    },
    {
      "id": 6,
      "image": "assets/images/doctors_department/heart.png",
      "department": "Cardiology Department",
    },
    {
      "id": 7,
      "image": "assets/images/doctors_department/pediatrics.png",
      "department": "Pediatrics Department"
    },
    {
      "id": 8,
      "image": "assets/images/doctors_department/skin.png",
      "department": "Dermatology Department"
    },
    {
      "id": 9,
      "image": "assets/images/doctors_department/maternity.png",
      "department": "Gynecology Department"
    },
    {
      "id": 10,
      "image": "assets/images/doctors_department/arthritis.png",
      "department": "Orthopedics Department"
    },
    {
      "id": 11,
      "image": "assets/images/doctors_department/x-ray.png",
      "department": "Radiology Department"
    },
  ];

//Doctors Lidt
  static List<Map> categoriesData = [
    {
      "id": 0,
      "image": "assets/images/doctors_department/x-ray.png",
      "department": "General Medicine",
      "doctors": [
        {
          "id": 1,
          "image": "assets/images/doctors_department/x-ray.png",
          "name": "Dr. Shihab K Saleem",
          "qualification": "MBBS, MD",
          "designation": "General Practitioner",
          "yearsOfExperience": 15,
          "visitedPatientCount": 500,
          "ratingOutOf5": 4.8,
          "consultationFee": 50,
        },
        {
          "id": 2,
          "image": "assets/images/doctors_department/cardiology.png",
          "name": "Dr. Emily Smith",
          "qualification": "MBBS, MD, FACC",
          "designation": "General Practitioner",
          "yearsOfExperience": 20,
          "visitedPatientCount": 700,
          "ratingOutOf5": 4.9,
          "consultationFee": 60,
        },
        {
          "id": 3,
          "image": "assets/images/doctors_department/dermatology.png",
          "name": "Dr. John Doe",
          "qualification": "MBBS, MD, DDVL",
          "designation": "General Practitioner",
          "yearsOfExperience": 12,
          "visitedPatientCount": 300,
          "ratingOutOf5": 4.5,
          "consultationFee": 55,
        },
        {
          "id": 4,
          "image": "assets/images/doctors_department/ent.png",
          "name": "Dr. Sarah Johnson",
          "qualification": "MBBS, MS",
          "designation": "General Practitioner",
          "yearsOfExperience": 18,
          "visitedPatientCount": 450,
          "ratingOutOf5": 4.7,
          "consultationFee": 65,
        },
        {
          "id": 5,
          "image": "assets/images/doctors_department/gastroenterology.png",
          "name": "Dr. Michael Brown",
          "qualification": "MBBS, MD, DM",
          "designation": "General Practitioner",
          "yearsOfExperience": 22,
          "visitedPatientCount": 800,
          "ratingOutOf5": 4.9,
          "consultationFee": 70,
        },
        {
          "id": 6,
          "image": "assets/images/doctors_department/obstetrics.png",
          "name": "Dr. Lisa Miller",
          "qualification": "MBBS, MS, DGO",
          "designation": "General Practitioner",
          "yearsOfExperience": 16,
          "visitedPatientCount": 600,
          "ratingOutOf5": 4.6,
          "consultationFee": 55,
        },
        {
          "id": 7,
          "image": "assets/images/doctors_department/orthopedics.png",
          "name": "Dr. Robert Wilson",
          "qualification": "MBBS, MS, MCh",
          "designation": "General Practitioner",
          "yearsOfExperience": 25,
          "visitedPatientCount": 1000,
          "ratingOutOf5": 4.8,
          "consultationFee": 75,
        },
        {
          "id": 8,
          "image": "assets/images/doctors_department/pediatrics.png",
          "name": "Dr. Maria Garcia",
          "qualification": "MBBS, MD, DCH",
          "designation": "General Practitioner",
          "yearsOfExperience": 14,
          "visitedPatientCount": 400,
          "ratingOutOf5": 4.5,
          "consultationFee": 50,
        },
        {
          "id": 9,
          "image": "assets/images/doctors_department/psychiatry.png",
          "name": "Dr. James Lee",
          "qualification": "MBBS, MD, DPM",
          "designation": "General Practitioner",
          "yearsOfExperience": 19,
          "visitedPatientCount": 550,
          "ratingOutOf5": 4.7,
          "consultationFee": 80,
        },
        {
          "id": 10,
          "image": "assets/images/doctors_department/surgery.png",
          "name": "Dr. Anna Wilson",
          "qualification": "MBBS, MS, MCh",
          "designation": "General Practitioner",
          "yearsOfExperience": 23,
          "visitedPatientCount": 900,
          "ratingOutOf5": 4.9,
          "consultationFee": 70,
        },
      ]
    },
    {
      "id": 2,
      "image": "assets/images/doctors_department/cardiology.png",
      "department": "Oncology Department",
      "doctors": [
        {
          "id": 1,
          "image": "assets/images/doctors_department/x-ray.png",
          "name": "Dr. Shihab K Saleem",
          "qualification": "MBBS, MD",
          "designation": "General Practitioner",
          "yearsOfExperience": 15,
          "visitedPatientCount": 500,
          "ratingOutOf5": 4.8,
          "consultationFee": 50,
        },
        {
          "id": 2,
          "image": "assets/images/doctors_department/cardiology.png",
          "name": "Dr. Emily Smith",
          "qualification": "MBBS, MD, FACC",
          "designation": "General Practitioner",
          "yearsOfExperience": 20,
          "visitedPatientCount": 700,
          "ratingOutOf5": 4.9,
          "consultationFee": 60,
        },
        {
          "id": 3,
          "image": "assets/images/doctors_department/dermatology.png",
          "name": "Dr. John Doe",
          "qualification": "MBBS, MD, DDVL",
          "designation": "General Practitioner",
          "yearsOfExperience": 12,
          "visitedPatientCount": 300,
          "ratingOutOf5": 4.5,
          "consultationFee": 55,
        },
        {
          "id": 4,
          "image": "assets/images/doctors_department/ent.png",
          "name": "Dr. Sarah Johnson",
          "qualification": "MBBS, MS",
          "designation": "General Practitioner",
          "yearsOfExperience": 18,
          "visitedPatientCount": 450,
          "ratingOutOf5": 4.7,
          "consultationFee": 65,
        },
        {
          "id": 5,
          "image": "assets/images/doctors_department/gastroenterology.png",
          "name": "Dr. Michael Brown",
          "qualification": "MBBS, MD, DM",
          "designation": "General Practitioner",
          "yearsOfExperience": 22,
          "visitedPatientCount": 800,
          "ratingOutOf5": 4.9,
          "consultationFee": 70,
        },
        {
          "id": 6,
          "image": "assets/images/doctors_department/obstetrics.png",
          "name": "Dr. Lisa Miller",
          "qualification": "MBBS, MS, DGO",
          "designation": "General Practitioner",
          "yearsOfExperience": 16,
          "visitedPatientCount": 600,
          "ratingOutOf5": 4.6,
          "consultationFee": 55,
        },
        {
          "id": 7,
          "image": "assets/images/doctors_department/orthopedics.png",
          "name": "Dr. Robert Wilson",
          "qualification": "MBBS, MS, MCh",
          "designation": "General Practitioner",
          "yearsOfExperience": 25,
          "visitedPatientCount": 1000,
          "ratingOutOf5": 4.8,
          "consultationFee": 75,
        },
        {
          "id": 8,
          "image": "assets/images/doctors_department/pediatrics.png",
          "name": "Dr. Maria Garcia",
          "qualification": "MBBS, MD, DCH",
          "designation": "General Practitioner",
          "yearsOfExperience": 14,
          "visitedPatientCount": 400,
          "ratingOutOf5": 4.5,
          "consultationFee": 50,
        },
        {
          "id": 9,
          "image": "assets/images/doctors_department/psychiatry.png",
          "name": "Dr. James Lee",
          "qualification": "MBBS, MD, DPM",
          "designation": "General Practitioner",
          "yearsOfExperience": 19,
          "visitedPatientCount": 550,
          "ratingOutOf5": 4.7,
          "consultationFee": 80,
        },
        {
          "id": 10,
          "image": "assets/images/doctors_department/surgery.png",
          "name": "Dr. Anna Wilson",
          "qualification": "MBBS, MS, MCh",
          "designation": "General Practitioner",
          "yearsOfExperience": 23,
          "visitedPatientCount": 900,
          "ratingOutOf5": 4.9,
          "consultationFee": 70,
        },
      ]
    },
    {
      "id": 3,
      "image": "assets/images/doctors_department/dermatology.png",
      "department": "Surgery Department",
      "name": "Dr. John Doe",
      "doctors": [
        {
          "id": 1,
          "image": "assets/images/doctors_department/x-ray.png",
          "name": "Dr. Shihab K Saleem",
          "qualification": "MBBS, MD",
          "consultationFee": 50,
        },
        {
          "id": 2,
          "image": "assets/images/doctors_department/cardiology.png",
          "name": "Dr. Emily Smith",
          "qualification": "MBBS, MD, FACC",
          "consultationFee": 60,
        },
        {
          "id": 3,
          "image": "assets/images/doctors_department/dermatology.png",
          "name": "Dr. John Doe",
          "qualification": "MBBS, MD, DDVL",
          "consultationFee": 55,
        },
        {
          "id": 4,
          "image": "assets/images/doctors_department/ent.png",
          "name": "Dr. Sarah Johnson",
          "qualification": "MBBS, MS",
          "consultationFee": 65,
        },
        {
          "id": 5,
          "image": "assets/images/doctors_department/gastroenterology.png",
          "name": "Dr. Michael Brown",
          "qualification": "MBBS, MD, DM",
          "consultationFee": 70,
        },
        {
          "id": 6,
          "image": "assets/images/doctors_department/obstetrics.png",
          "name": "Dr. Lisa Miller",
          "qualification": "MBBS, MS, DGO",
          "consultationFee": 55,
        },
        {
          "id": 7,
          "image": "assets/images/doctors_department/orthopedics.png",
          "name": "Dr. Robert Wilson",
          "qualification": "MBBS, MS, MCh",
          "consultationFee": 75,
        },
        {
          "id": 8,
          "image": "assets/images/doctors_department/pediatrics.png",
          "name": "Dr. Maria Garcia",
          "qualification": "MBBS, MD, DCH",
          "consultationFee": 50,
        },
        {
          "id": 9,
          "image": "assets/images/doctors_department/psychiatry.png",
          "name": "Dr. James Lee",
          "qualification": "MBBS, MD, DPM",
          "consultationFee": 80,
        },
        {
          "id": 10,
          "image": "assets/images/doctors_department/surgery.png",
          "name": "Dr. Anna Wilson",
          "qualification": "MBBS, MS, MCh",
          "consultationFee": 70,
        },
      ]
    },
    {
      "id": 4,
      "image": "assets/images/doctors_department/ent.png",
      "department": "Emergency Department",
      "name": "Dr. Sarah Johnson",
      "doctors": [
        {
          "id": 1,
          "image": "assets/images/doctors_department/x-ray.png",
          "name": "Dr. Shihab K Saleem",
          "qualification": "MBBS, MD",
          "consultationFee": 50,
        },
        {
          "id": 2,
          "image": "assets/images/doctors_department/cardiology.png",
          "name": "Dr. Emily Smith",
          "qualification": "MBBS, MD, FACC",
          "consultationFee": 60,
        },
        {
          "id": 3,
          "image": "assets/images/doctors_department/dermatology.png",
          "name": "Dr. John Doe",
          "qualification": "MBBS, MD, DDVL",
          "consultationFee": 55,
        },
        {
          "id": 4,
          "image": "assets/images/doctors_department/ent.png",
          "name": "Dr. Sarah Johnson",
          "qualification": "MBBS, MS",
          "consultationFee": 65,
        },
        {
          "id": 5,
          "image": "assets/images/doctors_department/gastroenterology.png",
          "name": "Dr. Michael Brown",
          "qualification": "MBBS, MD, DM",
          "consultationFee": 70,
        },
        {
          "id": 6,
          "image": "assets/images/doctors_department/obstetrics.png",
          "name": "Dr. Lisa Miller",
          "qualification": "MBBS, MS, DGO",
          "consultationFee": 55,
        },
        {
          "id": 7,
          "image": "assets/images/doctors_department/orthopedics.png",
          "name": "Dr. Robert Wilson",
          "qualification": "MBBS, MS, MCh",
          "consultationFee": 75,
        },
        {
          "id": 8,
          "image": "assets/images/doctors_department/pediatrics.png",
          "name": "Dr. Maria Garcia",
          "qualification": "MBBS, MD, DCH",
          "consultationFee": 50,
        },
        {
          "id": 9,
          "image": "assets/images/doctors_department/psychiatry.png",
          "name": "Dr. James Lee",
          "qualification": "MBBS, MD, DPM",
          "consultationFee": 80,
        },
        {
          "id": 10,
          "image": "assets/images/doctors_department/surgery.png",
          "name": "Dr. Anna Wilson",
          "qualification": "MBBS, MS, MCh",
          "consultationFee": 70,
        },
      ]
    },
    {
      "id": 5,
      "image": "assets/images/doctors_department/gastroenterology.png",
      "department": "Neurology Department",
      "name": "Dr. Michael Brown",
      "doctors": [
        {
          "id": 1,
          "image": "assets/images/doctors_department/x-ray.png",
          "name": "Dr. Shihab K Saleem",
          "qualification": "MBBS, MD",
          "consultationFee": 50,
        },
        {
          "id": 2,
          "image": "assets/images/doctors_department/cardiology.png",
          "name": "Dr. Emily Smith",
          "qualification": "MBBS, MD, FACC",
          "consultationFee": 60,
        },
        {
          "id": 3,
          "image": "assets/images/doctors_department/dermatology.png",
          "name": "Dr. John Doe",
          "qualification": "MBBS, MD, DDVL",
          "consultationFee": 55,
        },
        {
          "id": 4,
          "image": "assets/images/doctors_department/ent.png",
          "name": "Dr. Sarah Johnson",
          "qualification": "MBBS, MS",
          "consultationFee": 65,
        },
        {
          "id": 5,
          "image": "assets/images/doctors_department/gastroenterology.png",
          "name": "Dr. Michael Brown",
          "qualification": "MBBS, MD, DM",
          "consultationFee": 70,
        },
        {
          "id": 6,
          "image": "assets/images/doctors_department/obstetrics.png",
          "name": "Dr. Lisa Miller",
          "qualification": "MBBS, MS, DGO",
          "consultationFee": 55,
        },
        {
          "id": 7,
          "image": "assets/images/doctors_department/orthopedics.png",
          "name": "Dr. Robert Wilson",
          "qualification": "MBBS, MS, MCh",
          "consultationFee": 75,
        },
        {
          "id": 8,
          "image": "assets/images/doctors_department/pediatrics.png",
          "name": "Dr. Maria Garcia",
          "qualification": "MBBS, MD, DCH",
          "consultationFee": 50,
        },
        {
          "id": 9,
          "image": "assets/images/doctors_department/psychiatry.png",
          "name": "Dr. James Lee",
          "qualification": "MBBS, MD, DPM",
          "consultationFee": 80,
        },
        {
          "id": 10,
          "image": "assets/images/doctors_department/surgery.png",
          "name": "Dr. Anna Wilson",
          "qualification": "MBBS, MS, MCh",
          "consultationFee": 70,
        },
      ]
    },
    {
      "id": 6,
      "image": "assets/images/doctors_department/obstetrics.png",
      "department": "Cardiology Department",
      "name": "Dr. Lisa Miller",
      "doctors": [
        {
          "id": 1,
          "image": "assets/images/doctors_department/x-ray.png",
          "name": "Dr. Shihab K Saleem",
          "qualification": "MBBS, MD",
          "consultationFee": 50,
        },
        {
          "id": 2,
          "image": "assets/images/doctors_department/cardiology.png",
          "name": "Dr. Emily Smith",
          "qualification": "MBBS, MD, FACC",
          "consultationFee": 60,
        },
        {
          "id": 3,
          "image": "assets/images/doctors_department/dermatology.png",
          "name": "Dr. John Doe",
          "qualification": "MBBS, MD, DDVL",
          "consultationFee": 55,
        },
        {
          "id": 4,
          "image": "assets/images/doctors_department/ent.png",
          "name": "Dr. Sarah Johnson",
          "qualification": "MBBS, MS",
          "consultationFee": 65,
        },
        {
          "id": 5,
          "image": "assets/images/doctors_department/gastroenterology.png",
          "name": "Dr. Michael Brown",
          "qualification": "MBBS, MD, DM",
          "consultationFee": 70,
        },
        {
          "id": 6,
          "image": "assets/images/doctors_department/obstetrics.png",
          "name": "Dr. Lisa Miller",
          "qualification": "MBBS, MS, DGO",
          "consultationFee": 55,
        },
        {
          "id": 7,
          "image": "assets/images/doctors_department/orthopedics.png",
          "name": "Dr. Robert Wilson",
          "qualification": "MBBS, MS, MCh",
          "consultationFee": 75,
        },
        {
          "id": 8,
          "image": "assets/images/doctors_department/pediatrics.png",
          "name": "Dr. Maria Garcia",
          "qualification": "MBBS, MD, DCH",
          "consultationFee": 50,
        },
        {
          "id": 9,
          "image": "assets/images/doctors_department/psychiatry.png",
          "name": "Dr. James Lee",
          "qualification": "MBBS, MD, DPM",
          "consultationFee": 80,
        },
        {
          "id": 10,
          "image": "assets/images/doctors_department/surgery.png",
          "name": "Dr. Anna Wilson",
          "qualification": "MBBS, MS, MCh",
          "consultationFee": 70,
        },
      ]
    },
    {
      "id": 7,
      "image": "assets/images/doctors_department/orthopedics.png",
      "department": "Pediatrics Department",
      "doctors": [],
    },
    {
      "id": 8,
      "image": "assets/images/doctors_department/pediatrics.png",
      "department": "Dermatology Department",
      "doctors": [],
    },
    {
      "id": 9,
      "image": "assets/images/doctors_department/psychiatry.png",
      "department": "Gynecology Department",
      "doctors": [],
    },
    {
      "id": 10,
      "image": "assets/images/doctors_department/surgery.png",
      "department": "Orthopedics Department",
      "doctors": [],
    },
    {
      "id": 11,
      "image": "assets/images/doctors_department/surgery.png",
      "department": "Radiology Department",
      "doctors": [],
    },
  ];
}
